### PR TITLE
Add colorProperty option to enable property-specific themes

### PR DESCRIPTION
**Pull request by kaelansmith**
Hi @ankarhem, first off thanks for the great package -- simple and effective!

This PR adds support for applying a Theme to specific Tailwind theme color properties -- so essentially `backgroundColor` can have a different theme than `textColor`. The package currently limits you to applying a theme to the broad `colors` property (which applies to all colors like background, text, borders, etc.).

Here's some background on why/how I ended up needing this solution: I started using ShadcnUI and its CSS variable theming approach (I came across the Tailwind Easy Theme package because you commented on a ShadcnUI GH issue). I ended up disliking ShadcnUI's color naming convention; specifically color pairings like `bg-primary` and `text-primary-foregound` felt a bit redundant and long. Why should we need "foreground" if "text-" already implies it's a foreground item?

Problem is, if you pair `bg-primary` and `text-primary`, you get the same colors and therefore can't read the text. So I looked into how to make "-primary" equate to different colors in different contexts, eg. `bg-primary` == #FFF, but `text-primary` == #000. I found this great [article by Martin Schindler](https://mrtnschndlr.medium.com/things-to-rethink-with-tailwind-css-part-2-colors-6664c8079cfc), who came to the same conclusions as me and provided the solution: 

In tailwind.config.js, you can specify colors more granularly like so:
```js
// tailwind.config.js

module.exports = {
  theme: {
    backgroundColor: {
      normal: "white",
      inverted: "black",
      ...
    },
    textColor: {
      normal: "black",
      inverted: "white",
      ...
    }
  },
}
```

So, this PR adds `colorProperty` to the Theme class' `Options` parameter, where you can specify a single Tailwind color theme property, or an array of properties, which ensures that when `Theme.create()` runs, the generated `themeSettings` get applied to the specified `colorProperty`; it defaults to `colors`, so **this doesn't introduce any breaking changes.**

Example of two themes that apply to `textColor` (i.e. `text-*` classes) and `backgroundColor` (i.e. `bg-*` classes):
```js
// note: `brand` is an object containing the HEX codes
const textTheme = new Theme(
  {
    root: {
      DEFAULT: brand.neutral[950],
      dim: brand.neutral[700],
      muted: brand.neutral[500],
      invert: brand.neutral[200],
    },
    primary: brand.neutral[50],
    link: brand.blue[500],
    secondary: brand.neutral[800],
    destructive: brand.neutral[50]
  },
  {
    prefix: '--text-color-',
    colorProperty: 'textColor',
  }
);

const bgTheme = new Theme(
  {
    root: {
      DEFAULT: brand.white,
      dim: brand.neutral[100],
      invert: brand.neutral[700],
    },
    primary: brand.blue[500],
    destructive: brand.red.light,
  },
  {
    prefix: '--bg-color-',
    colorProperty: 'backgroundColor',
  }
);
```

Then of course you can apply Theme variants to each one separately, as usual. Note that in this example, the two themes share some color names, but apply different colors, AND also have some different/unique colors (eg. you can use `text-link` but not `bg-link`).

This adds a lot more flexibility to your library, and enables some much nicer color naming conventions that I think will start to become more popular. Let me know your thoughts, if you have any feedback etc.. I'd be happy to add some README documentation for this feature to this PR if you intend on accepting it.

Btw I'm planning on baking Tailwind Easy Theme into a free website template for my OSS project, CloakWP -- which may or may not bring you some new users :)

### CODE REVIEW

**Comment by ankarhem** [comment]
Hey @kaelansmith, thanks for a thorough description!

If I understand correctly, in this example textTheme and bgTheme are not _really_ two themes, but written as such because you want the syntax of bg-primary / text-primary. This makes me think it is perhaps better to change the input to theme instead.

What do you think about changing the input to Theme to be exactly the input to tailwind config's theme?

Then migrations would be:

```diff
const theme = new Theme({
--  primary: {
--    DEFAULT: '#ffcccc',
--    100: '#ffcccc',
--    200: '#ff9999',
--    300: '#ff6666',
--    400: '#ff3333',
--  },
++  colors: {
++    primary: {
++      DEFAULT: '#ffcccc',
++      100: '#ffcccc',
++      200: '#ff9999',
++      300: '#ff6666',
++      400: '#ff3333',
++    },
++  },
});
```

And would support this with:

```typescript
const theme = new Theme({
    backgroundColor: {
      normal: "white",
      inverted: "black",
      ...
    },
    textColor: {
      normal: "black",
      inverted: "white",
      ...
    }
})
```

I think this would make more sense, since you would have to define the default values in this theme to be able to create variants for it. I suppose, you still _could_ create this as two different themes if you have a selector for bg theme and text theme 🤔 ? Not sure atm though.

A benefit of this approach is that migrating from regular tailwind -> tailwind-easy-theme would be copy paste.

I suppose you could also theme fonts etc. as well with this.

What do you think?

**Comment by kaelansmith** [comment]
Yeah that's definitely a nicer API pattern for all the reasons you pointed out. We would have to handle creating unique CSS property prefixes under-the-hood for each theme property to avoid conflicts between them. For example, this:

```js
const theme = new Theme({
    backgroundColor: {
      normal: "white",
      inverted: "black",
      ...
    },
    textColor: {
      normal: "black",
      inverted: "white",
      ...
    }
})
```

... would result in:

```css
--text-color-normal
--text-color-inverted
--bg-color-normal
--bg-color-inverted
```
... and custom prefixes would have to prefix the auto-generated prefixes, for example:

```js
const theme = new Theme({
    backgroundColor: {
      normal: "white",
      inverted: "black",
      ...
    },
    textColor: {
      normal: "black",
      inverted: "white",
      ...
    }
},
{
    prefix: 'custom',
})
```

... would result in:

```css
--custom-text-color-normal
--custom-text-color-inverted
--custom-bg-color-normal
--custom-bg-color-inverted
```

As for supporting non-color properties like fonts, I guess you'd just have to handle splitting out the color properties from the rest so you don't apply the HSL logic for example on fontSizes. Personally the only non-color property I can imagine using in a theme is `boxShadow` -- eg. to customize shadows in dark mode.. maybe you leave non-color property support for a future version? Up to you obviously!

**Comment by ankarhem** [comment]
Sounds good, we can keep a list around (or if the css variable mapping is solved using table, maybe we can use that for this as well) for what we support and filter with that. Regarding css variable names i think they should be (assuming the default prefix `--color-`:

```css
--color-primary
--color-text-primary
--color-bg-primary
--color-border-primary
```

Do you feel up to the task?

**Review by Krabba — APPROVED** [review]

**Comment by kaelansmith** [comment]
@ankarhem I have a working version locally, just need to test a few things more and clean things up. Hoping to find time this weekend to wrap it up.

**Comment by kaelansmith** [comment]
@ankarhem alright got a fully working version ready for you to test now. It's a pretty big refactor and I'm stoked about what it enables. It follows the exact API design you laid out:

```js
const theme = new Theme({
    colors: {
      normal: "white",
    },
    textColor: {
      normal: "black",
    },
    backgroundColor: {
      normal: "gray",
    },
    borderColor: {
      normal: "gray",
    },
    // ...etc
}
```

which results in these CSS variables (with the same HSL-converted values + HEX fallback as before):

```
--color-normal
--color-text-normal
--color-bg-normal
--color-border-normal
```

It also supports all other CSS properties! It just doesn't apply any custom value conversion logic like the colors do. For example:

```js
const theme = new Theme({
    borderRadius: {
      lg: `var(--radius)`,
    }
    // ...etc
}
```

results in:

```
:root {
   --border-radius-lg: var(--radius);
}

.rounded-lg {
   border-radius: var(--border-radius-lg);
}
```

I also tested variants with non-color properties -- eg. dark mode can now have different border radiuses than light mode (not the most practical example, but you get the idea).

The way the code is architected also makes it very easy for us (internally) to build special conversion logic for other properties later on; check out how `ColorProperty` is implemented for an example. I can imagine it being very trivial to (in a future version, if we wanted to) expose a user-facing Theme Property Config API to allow users to map properties to their own ThemeProperty child classes, to essentially specify their own CSS value conversion logic -- i.e. they could create their own versions of the `ColorProperty` class and map to whatever properties they want via a config (check out the `themePropertiesConfig` in `/src/Theme.ts` to see what I mean).

Important to note this introduces a breaking change. Existing users would have to update their Theme configs like so:

```diff
- const theme = new Theme({
-    primary: "#000",
-    secondary: "#FFF"
- });
+ const theme = new Theme({
+    colors: {
+       primary: "#000",
+       secondary: "#FFF"
+    }
+ }) ;
```

Looking forward to hearing your thoughts/feedback. Still need to add README updates, but I'll wait till we finalize things.

**Comment by ankarhem** [comment]
Is there any particular reason why border radius was made to "nest" css variables? I would've assumed the config would be to set the value. Like this:

```typescript
const theme = new Theme({
    borderRadius: {
      lg: '1rem',
    }
    // ...etc
}
```

```css
:root {
   --border-radius-lg: 1rem;
}

.rounded-lg {
   border-radius: var(--border-radius-lg);
}
```

**Comment by kaelansmith** [comment]
Using `var(--radius)` as below is simply a user decision, the package doesn't expect users to do that, and doesn't handle things any differently than if I set it to `1rem` instead. I personally use it to set a "base" radius in my own CSS file which the other radius variants get calculated from (i.e. provides a single place to update border radius' site-wide -- useful for a reusable template), for example:

```js
const theme = new Theme({
    borderRadius: {
        lg: `var(--radius)`,
        md: `calc(var(--radius) - 2px)`,
        sm: 'calc(var(--radius) - 4px)',
      }
    // ...etc
}
```
The package simply dumps whatever the user provides like so:
```css
:root {
   --border-radius-lg: USER_VALUE;
}

.rounded-lg {
   border-radius: var(--border-radius-lg);
}
```

So the nested CSS variables in my example is expected, and a user decision.

**Comment by kaelansmith** [comment]
@ankarhem happy new year :) resurfacing this — any thoughts/concerns/feedback? Or anything I can do to push this PR along? I personally will need these changes in production in the next couple weeks, so please let me know if you aren’t keen on merging this as I’ll need to publish it as a new/separate package

**Comment by ankarhem** [comment]
> @ankarhem happy new year :) resurfacing this — any thoughts/concerns/feedback? Or anything I can do to push this PR along? I personally will need these changes in production in the next couple weeks, so please let me know if you aren’t keen on merging this as I’ll need to publish it as a new/separate package

Hey! Same to you. I have not really had the time is all. I'll make sure we can merge this soon.

**Review by ankarhem — APPROVED** [review]

**Comment by ankarhem** [comment]
@kaelansmith Great work with this, I'll go ahead and merge it.

**Comment by ankarhem** [comment]
It's now [published as v2.0.0](https://www.npmjs.com/package/tailwind-easy-theme)

**Pull request merged**
